#ifndef PWMK_CODE_CONVERT_H
#define PWMK_CODE_CONVERT_H

#include "keyboard/code.h"
#include <stdbool.h>
#include <stdint.h>

typedef enum {
  VIAL_KEYCODE_MUTE = 0x00A8,
  VIAL_KEYCODE_VOLUME_UP = 0x00A9,
  VIAL_KEYCODE_VOLUME_DOWN = 0x00AA,
  VIAL_KEYCODE_MEDIA_NEXT_TRACK = 0x00AB,
  VIAL_KEYCODE_MEDIA_PREV_TRACK = 0x00AC,
  VIAL_KEYCODE_MEDIA_STOP = 0x00AD,
  VIAL_KEYCODE_MEDIA_PLAY_PAUSE = 0x00AE,
  VIAL_KEYCODE_MEDIA_EJECT = 0x00B0,
  VIAL_KEYCODE_MEDIA_FAST_FORWARD = 0x00BB,
  VIAL_KEYCODE_MEDIA_REWIND = 0x00BC,
  VIAL_KEYCODE_MOUSE_UP = 0x00CD,
  VIAL_KEYCODE_MOUSE_DOWN = 0x00CE,
  VIAL_KEYCODE_MOUSE_LEFT = 0x00CF,
  VIAL_KEYCODE_MOUSE_RIGHT = 0x00D0,
  VIAL_KEYCODE_MOUSE_BUTTON_1 = 0x00D1,
  VIAL_KEYCODE_MOUSE_BUTTON_2 = 0x00D2,
  VIAL_KEYCODE_MOUSE_BUTTON_3 = 0x00D3,
  VIAL_KEYCODE_MOUSE_BUTTON_4 = 0x00D4,
  VIAL_KEYCODE_MOUSE_BUTTON_5 = 0x00D5,
  VIAL_KEYCODE_MOUSE_BUTTON_6 = 0x00D6,
  VIAL_KEYCODE_MOUSE_BUTTON_7 = 0x00D7,
  VIAL_KEYCODE_MOUSE_BUTTON_8 = 0x00D8,
  VIAL_KEYCODE_MOUSE_WHEEL_UP = 0x00D9,
  VIAL_KEYCODE_MOUSE_WHEEL_DOWN = 0x00DA,
  VIAL_KEYCODE_MOUSE_WHEEL_LEFT = 0x00DB,
  VIAL_KEYCODE_MOUSE_WHEEL_RIGHT = 0x00DC,
  VIAL_KEYCODE_LEFT_CONTROL = 0x00E0,
  VIAL_KEYCODE_LEFT_SHIFT = 0x00E1,
  VIAL_KEYCODE_LEFT_ALT = 0x00E2,
  VIAL_KEYCODE_LEFT_GUI = 0x00E3,
  VIAL_KEYCODE_RIGHT_CONTROL = 0x00E4,
  VIAL_KEYCODE_RIGHT_SHIFT = 0x00E5,
  VIAL_KEYCODE_RIGHT_ALT = 0x00E6,
  VIAL_KEYCODE_RIGHT_GUI = 0x00E7,
  VIAL_KEYCODE_CONNECTION_AUTO = 0x7780,
  VIAL_KEYCODE_CONNECTION_NEXT = 0x7781,
  VIAL_KEYCODE_CONNECTION_BLE = 0x7786,
  VIAL_KEYCODE_BLE_UNPAIR = 0x7792,
  VIAL_KEYCODE_BLE_SLOT_1 = 0x7793,
  VIAL_KEYCODE_BLE_SLOT_2 = 0x7794,
  VIAL_KEYCODE_BLE_SLOT_3 = 0x7795,
  VIAL_KEYCODE_BLE_SLOT_4 = 0x7796,
  VIAL_KEYCODE_BLE_SLOT_5 = 0x7797,
  VIAL_KEYCODE_BOOTLOADER = 0x7C00,
  VIAL_KEYCODE_USER_START = 0x7E40,
  VIAL_KEYCODE_USER_END = 0x7E5F,
  VIAL_KEYCODE_USER_COUNT = VIAL_KEYCODE_USER_END - VIAL_KEYCODE_USER_START + 1,
} vial_keycode_t;

bool code_convert_to_vial(icode_t keycode_internal, uint16_t *keycode_vial);
bool code_convert_to_internal(uint16_t keycode_vial, icode_t *keycode_internal);
bool code_convert_is_dangerous_vial_code(uint16_t keycode_vial);

#endif // PWMK_CODE_CONVERT_H
